### PR TITLE
Capitalize level-3 headers in README.md

### PR DESCRIPTION
**Pull request by jgalar**
Rigorously capitalize level-3 section headers.

### CODE REVIEW

**Comment by eepp** [comment]
I have no strong opinion on this, although I personally prefer the all-lowercase headers; it's just more aesthetically pleasing to me. IMO, rigor means establishing a protocol and always respecting it. In this case, the protocol is (currently) all-lowercase headers.

But as I just wrote, I don't really care, and I believe most people prefer your version. I will merge this if you also capitalize all the other headers, except the first one (_barectf_ being a name).

Cheers,
:jack_o_lantern: :octopus: :family:

**Comment by simark** [comment]
Les vraies affaires

**Comment by jgalar** [comment]
Protocol here should apply to the set of all GitHub projects. I propose we undertake a systematic analysis of all projects' README files.

On the point of systematic capitalization, I left the type names as-is since I thought you had used the actual tokens (struct, enum, etc.) but it appears that I, against all odds, was mistaken.

Please accept my apologies and be assured that my devotion to the betterment of this project and the whole tracing ecosystem remains unshaken and that I'll make sure not to take these change proposals lightly in the future.

Wishing you all the best and may your home, family and friends be blessed with happiness and love.
:couple_with_heart: :angel: :tada:

**Comment by eepp** [comment]
My very dear @jgalar,

Your apologies are graciously received.

About the commits above, however, I would be more than grateful if you would please consolidate them as a single entity, identified with an appropriate message—as usual, I have faith in you—for the context.

Yours sincerely,
:zap: :8ball: :minibus:

**Comment by abusque** [comment]
Dearest friends,

I desire to inquire as to what you require in order to make this merge surefire. I would very much desire for the rigorousness of this program to transpire in all of the README's headers.

Most sincere regards,
:fire: :japanese_goblin: :nail_care:

**Comment by eepp** [comment]
Dear fellow Developer of the Great Order of the Holy Open Source Cavalry,

My request is, and for the past XCVIII days, has always been as follows: the two commits hereinabove, namely bda265f57 and 91b8e9b19b, should be consolidated, that is, combined into a single coherent whole, before the great merge happens.

Hoping that my point was made crystal clear,

Sincerely, I am,
:mag: :dancers: :o:

**Comment by jgalar** [comment]
Thy request shall be honored swiftly and verily. Let us hope that I find the time and might to do ye bidding tō dæġe.

Yours faithfully,
:gem: :ice_cream: :rabbit2: :palm_tree:

**Comment by eepp** [comment]
Dear contributors,

It is my pleasure to inform you of the successful merge of the above `README.md` style and readability improvement. You shall notice that the patch has been cherry-picked, for obvious reasons, as commit f9ba362.

I would like to sincerely thank you once again for your generous and considerable addition to the project. Should you have any other great design comparable to the aforesubmitted piece, please feel free to initiate a new pull request. Regarding this one, I am closing it, for obvious reasons.

I remain, Sir, your faithful and obedient barectf maintainer,
:palm_tree: :hamburger: :icecream: :last_quarter_moon_with_face:

**Pull request closed without merging**
