### PR TITLE
barectf: add support for packet sequence number

### LINKED ISSUE #23: Is it possible to include a packet sequence count?
Looking through the docs under packet features, it doesn't look like including a `packet_seq_num` is supported.
If I didn't overlook the docs, is this a feature that would be considered given that it's called out in the spec?
It'd be really handy to have this in the CTF packet rather than having to manage it elsewhere.

### PR DESCRIPTION
**Pull request by jonlamb-gh**
Adds a new optional packet features object `seq-num-field-type`,
which generates the metadata field type name `packet_seq_num` when
defined (defaults to false).
Currently this is conditionally maintained in `struct barectf_ctx` as
a `uint32_t` type like `events_discarded`.
In the future this could be improved to use the config type defined
by the stream in `struct barectf_default_ctx` so that the types are aligned.

Closes #23

Signed-off-by: Jon Lamb <jon@auxon.io>

### CODE REVIEW

**Comment by eepp** [comment]
May I kindly ask you to submit this patch to [barectf's Gerrit](https://review.lttng.org/admin/repos/barectf,access) instead?

Review will be much more easier this way.

**Comment by eepp** [comment]
> May I kindly ask you to submit this patch to [barectf's Gerrit](https://review.lttng.org/admin/repos/barectf,access) instead?

I can assist if you're not familiar.

**Comment by jonlamb-gh** [comment]
:+1: 
First time with Gerrit, but I think I got it:
https://review.lttng.org/c/barectf/+/7496

**Comment by eepp** [comment]
> First time with Gerrit, but I think I got it:

🥳 Thank you!

Closing this PR as I'll merge into `master` directly from Gerrit.

**Pull request closed without merging**
